language: node_js

cache:
  directories:
    - $HOME/.npm
    - node_modules

sudo: false

notifications:
  email: false

node_js:
  - '9'

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"

before_install:
  - export CHROME_BIN=chromium-browser

before_script:
  - npm prune

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start